// Mirrors the ENUM names from the AppPermission.java file from the PssAdminServer
// Used for referencing the permission name returned in a user's UserDetails
export const APP_PERMISSION_CONSTRUCTION_ADD = "CONSTRUCTION_ADD";
export const APP_PERMISSION_CONSTRUCTION_DELETE = "CONSTRUCTION_DELETE";
export const APP_PERMISSION_CONSTRUCTION_EDIT = "CONSTRUCTION_EDIT";
export const APP_PERMISSION_CONSTRUCTION_HWY_C_PROGRESS_SPECIAL_FIELDS_EDIT =
  "CONSTRUCTION_HWY_C_PROGRESS_SPECIAL_FIELDS_EDIT";
export const APP_PERMISSION_CONSTRUCTION_LETTER_OF_MATERIAL_CERTS_FROM_HWY_L_FIELDS_EDIT =
  "CONSTRUCTION_LETTER_OF_MATERIAL_CERTS_FROM_HWY_L_FIELDS_EDIT";
export const APP_PERMISSION_CONSTRUCTION_OFFICE_CS_FIRM_EDIT =
  "CONSTRUCTION_OFFICE_CS_FIRM_EDIT";
export const APP_PERMISSION_CONSTRUCTION_OFFICE_PD_FIRM_EDIT =
  "CONSTRUCTION_OFFICE_PD_FIRM_EDIT";
export const APP_PERMISSION_CONSTRUCTION_PROJECT_STATUS_EDIT =
  "CONSTRUCTION_PROJECT_STATUS_EDIT";
export const APP_PERMISSION_CONSTRUCTION_PROJECT_STATUS_FISCAL_CLOSEOUT_PENDING_EDIT =
  "CONSTRUCTION_PROJECT_STATUS_FISCAL_CLOSEOUT_PENDING_EDIT";
export const APP_PERMISSION_COUNTY_ADD = "COUNTY_ADD";
export const APP_PERMISSION_COUNTY_DELETE = "COUNTY_DELETE";
export const APP_PERMISSION_COUNTY_EDIT = "COUNTY_EDIT";
export const APP_PERMISSION_COUNTY_PROJECT_STATUS_EDIT =
  "COUNTY_PROJECT_STATUS_EDIT";
export const APP_PERMISSION_COUNTY_SPECIAL_FIELDS_EDIT =
  "COUNTY_SPECIAL_FIELDS_EDIT";
export const APP_PERMISSION_DESIGN_ADD = "DESIGN_ADD";
export const APP_PERMISSION_DESIGN_DELETE = "DESIGN_DELETE";
export const APP_PERMISSION_DESIGN_EDIT = "DESIGN_EDIT";
export const APP_PERMISSION_DESIGN_PROJECT_STATUS_EDIT =
  "DESIGN_PROJECT_STATUS_EDIT";
export const APP_PERMISSION_FEDERAL_CURRENT_POP_DATE_FIELDS_EDIT =
  "FEDERAL_CURRENT_POP_DATE_FIELDS_EDIT";
export const APP_PERMISSION_FEDERAL_EDIT = "FEDERAL_EDIT";
export const APP_PERMISSION_FEDERAL_FV_REQUEST_FIELDS_EDIT =
  "FEDERAL_FV_REQUEST_FIELDS_EDIT";
export const APP_PERMISSION_FEDERAL_INTERNAL_NOTES_EDIT =
  "FEDERAL_INTERNAL_NOTES_EDIT";
export const APP_PERMISSION_FEDERAL_ORIGINAL_POP_DATE_FIELDS_EDIT =
  "FEDERAL_ORIGINAL_POP_DATE_FIELDS_EDIT";
export const APP_PERMISSION_FEDERAL_PE10_FIELDS_EDIT =
  "FEDERAL_PE10_FIELDS_EDIT";
export const APP_PERMISSION_FEDERAL_POP_DT_ALL_BUTTON_ACCESS =
  "FEDERAL_POP_DT_ALL_BUTTON_ACCESS";
export const APP_PERMISSION_FEDERAL_QTR_PE_10_BUTTON_ACCESS =
  "FEDERAL_QTR_PE_10_BUTTON_ACCESS";
export const APP_PERMISSION_FEDERAL_EXTENSION_EDIT = "FEDERAL_EXTENSION_EDIT";
export const APP_PERMISSION_FEDERAL_EXTENSION_ADD = "FEDERAL_EXTENSION_ADD";
export const APP_PERMISSION_FEDERAL_EXTENSION_DELETE =
  "FEDERAL_EXTENSION_DELETE";
export const APP_PERMISSION_MATERIAL_CERTIFICATION_ADD =
  "MATERIAL_CERTIFICATION_ADD";
export const APP_PERMISSION_MATERIAL_CERTIFICATION_DELETE =
  "MATERIAL_CERTIFICATION_DELETE";
export const APP_PERMISSION_MATERIAL_CERTIFICATION_EDIT =
  "MATERIAL_CERTIFICATION_EDIT";
export const APP_PERMISSION_MENU_PROJECT_LOG_ACCESS = "MENU_PROJECT_LOG_ACCESS";
export const APP_PERMISSION_MENU_ROW_UA_LOG_EDIT_ACCESS =
  "MENU_ROW_UA_LOG_EDIT_ACCESS";
export const APP_PERMISSION_MENU_SYSTEM_ADMINISTRATION_ACCESS =
  "MENU_SYSTEM_ADMINISTRATION_ACCESS";
export const APP_PERMISSION_MENU_SYSTEM_ADMINISTRATION_ORG_UNIT_ACCESS =
  "MENU_SYSTEM_ADMINISTRATION_ORG_UNIT_ACCESS";
export const APP_PERMISSION_MENU_SYSTEM_ADMINISTRATION_ROLE_ACCESS =
  "MENU_SYSTEM_ADMINISTRATION_ROLE_ACCESS";
export const APP_PERMISSION_MENU_SYSTEM_ADMINISTRATION_USER_ACCESS =
  "MENU_SYSTEM_ADMINISTRATION_USER_ACCESS";
export const APP_PERMISSION_PLANNING_ADD = "PLANNING_ADD";
export const APP_PERMISSION_PLANNING_DESIGN_CURRENT_PHASE_EDIT =
  "PLANNING_DESIGN_CURRENT_PHASE_EDIT";
export const APP_PERMISSION_PLANNING_DELETE = "PLANNING_DELETE";
export const APP_PERMISSION_PLANNING_EDIT = "PLANNING_EDIT";
export const APP_PERMISSION_PLANNING_PROJECT_STATUS_EDIT =
  "PLANNING_PROJECT_STATUS_EDIT";
export const APP_PERMISSION_PROGRAMMED_EDIT = "PROGRAMMED_EDIT";
export const APP_PERMISSION_PROGRAMMED_ADD = "PROGRAMMED_ADD";
export const APP_PERMISSION_PROGRAMMED_DELETE = "PROGRAMMED_DELETE";
export const APP_PERMISSION_PROGRAMMED_PROJECT_STATUS_EDIT =
  "PROGRAMMED_PROJECT_STATUS_EDIT";

export const APP_PERMISSION_EXPENDITURE_EDIT = "EXPENDITURE_EDIT";
export const APP_PERMISSION_EXPENDITURE_ADD = "EXPENDITURE_ADD";
export const APP_PERMISSION_EXPENDITURE_DELETE = "EXPENDITURE_DELETE";
export const APP_PERMISSION_EXPENDITURE_PROJECT_STATUS_EDIT =
  "EXPENDITURE_PROJECT_STATUS_EDIT";

export const APP_PERMISSION_PROJECT_106_PROCESS_DETAILS_PRIORITY_SORT_CATEGORY_EDIT =
  "PROJECT_106_PROCESS_DETAILS_PRIORITY_SORT_CATEGORY_EDIT";
export const APP_PERMISSION_PROJECT_ADMIN_PRIORITY_EDIT =
  "PROJECT_ADMIN_PRIORITY_EDIT";
export const APP_PERMISSION_PROJECT_ANT_OBLIG_OSR_EDIT =
  "PROJECT_ANT_OBLIG_OSR_EDIT";
export const APP_PERMISSION_PROJECT_ARCHIVE_EDIT = "PROJECT_ARCHIVE_EDIT";
export const APP_PERMISSION_PROJECT_BRIDGE_ID_EDIT = "PROJECT_BRIDGE_ID_EDIT";
export const APP_PERMISSION_PROJECT_CATEGORY_AND_SUB_CATEGORY_EDIT =
  "PROJECT_CATEGORY_AND_SUB_CATEGORY_EDIT";
export const APP_PERMISSION_PROJECT_FEDERAL_ID_EDIT = "PROJECT_FEDERAL_ID_EDIT";
export const APP_PERMISSION_PROJECT_FEDERAL_PE1_PE2_COMP_DATE_EDIT =
  "PROJECT_FEDERAL_PE1_PE2_COMP_DATE_EDIT";
export const APP_PERMISSION_PROJECT_ISLAND_EDIT = "PROJECT_ISLAND_EDIT";
export const APP_PERMISSION_PROJECT_OFFICE_LIST_EDIT =
  "PROJECT_OFFICE_LIST_EDIT";
export const APP_PERMISSION_PROJECT_PEOPLE_LIST_EDIT =
  "PROJECT_PEOPLE_LIST_EDIT";
export const APP_PERMISSION_PROJECT_PROJECT_NUMBER_EDIT =
  "PROJECT_PROJECT_NUMBER_EDIT";
export const APP_PERMISSION_PROJECT_PROJECT_STATUS_TO_BE_FINALIZED_EDIT =
  "PROJECT_PROJECT_STATUS_TO_BE_FINALIZED_EDIT";
export const APP_PERMISSION_PROJECT_PROJECT_TITLE_EDIT =
  "PROJECT_PROJECT_TITLE_EDIT";
export const APP_PERMISSION_PROJECT_ROUTE_NO_AND_LEGISLATIVE_DISTRICTS_ADD =
  "PROJECT_ROUTE_NO_AND_LEGISLATIVE_DISTRICTS_ADD";
export const APP_PERMISSION_PROJECT_ROUTE_NO_AND_LEGISLATIVE_DISTRICTS_DELETE =
  "PROJECT_ROUTE_NO_AND_LEGISLATIVE_DISTRICTS_DELETE";
export const APP_PERMISSION_PROJECT_ROUTE_NO_AND_LEGISLATIVE_DISTRICTS_EDIT =
  "PROJECT_ROUTE_NO_AND_LEGISLATIVE_DISTRICTS_EDIT";
export const APP_PERMISSION_PROJECT_TRANSFER_FIELDS_EDIT =
  "PROJECT_TRANSFER_FIELDS_EDIT";
export const APP_PERMISSION_PROJECT_UTILITY_AGREEMENT_ADD =
  "PROJECT_UTILITY_AGREEMENT_ADD";
export const APP_PERMISSION_PROJECT_UTILITY_AGREEMENT_DELETE =
  "PROJECT_UTILITY_AGREEMENT_DELETE";
export const APP_PERMISSION_PROJECT_UTILITY_AGREEMENT_EDIT =
  "PROJECT_UTILITY_AGREEMENT_EDIT";
export const APP_PERMISSION_PROJECT_FED_MATCH_EDIT = "PROJECT_FED_MATCH_EDIT";
export const APP_PERMISSION_ROW_ADD = "ROW_ADD";
export const APP_PERMISSION_ROW_DELETE = "ROW_DELETE";
export const APP_PERMISSION_ROW_EDIT = "ROW_EDIT";
export const APP_PERMISSION_ROW_FEDERAL_POP_END_DATE_EDIT =
  "ROW_FEDERAL_POP_END_DATE_EDIT";
export const APP_PERMISSION_ROW_PROJECT_STATUS_EDIT = "ROW_PROJECT_STATUS_EDIT";
export const APP_PERMISSION_SYSTEM_ADMINISTRATION_ORG_UNIT_ADD =
  "SYSTEM_ADMINISTRATION_ORG_UNIT_ADD";
export const APP_PERMISSION_SYSTEM_ADMINISTRATION_ORG_UNIT_DELETE =
  "SYSTEM_ADMINISTRATION_ORG_UNIT_DELETE";
export const APP_PERMISSION_SYSTEM_ADMINISTRATION_ORG_UNIT_EDIT =
  "SYSTEM_ADMINISTRATION_ORG_UNIT_EDIT";
export const APP_PERMISSION_SYSTEM_ADMINISTRATION_ROLE_ADD =
  "SYSTEM_ADMINISTRATION_ROLE_ADD";
export const APP_PERMISSION_SYSTEM_ADMINISTRATION_ROLE_DELETE =
  "SYSTEM_ADMINISTRATION_ROLE_DELETE";
export const APP_PERMISSION_SYSTEM_ADMINISTRATION_ROLE_EDIT =
  "SYSTEM_ADMINISTRATION_ROLE_EDIT";
export const APP_PERMISSION_SYSTEM_ADMINISTRATION_USER_ADD =
  "SYSTEM_ADMINISTRATION_USER_ADD";
export const APP_PERMISSION_SYSTEM_ADMINISTRATION_USER_DELETE =
  "SYSTEM_ADMINISTRATION_USER_DELETE";
export const APP_PERMISSION_SYSTEM_ADMINISTRATION_USER_EDIT =
  "SYSTEM_ADMINISTRATION_USER_EDIT";
