// compData.js

export const initialData = {
    compUuid: 0,
    compSector: "",
    compGroup: "",
    compEng: "",
    compKor: "",
    compAbb: "",
    compColor: "",
    logoFile: "",
    estDate: "",
    compRate: "",
    hotelRate: "",
    optionRate: "",
    rentcarRate: "",
    restaurantRate: "",
    packRegRate: "",
    packRate: "",
    honeymoonRegRate: "",
    honeymoonRate: "",
    minAge: "",
    childAge: "",
    youthAge: "",
    couponYn: "",
    prepaidHow: "",
    beginDt: "",
    endDt: "",
    createdDt: "",
    createUser: "",
    modifyUser: "",
    modifiedDt: "",
};
