INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_lvl, use_yn, created_dt, modified_dt) VALUES ('183','오아후','Oahu','Oahu','3','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_lvl, use_yn, created_dt, modified_dt) VALUES ('183','빅아일랜드','Island of Hawaii','Island of Hawaii','3','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_lvl, use_yn, created_dt, modified_dt) VALUES ('183','마우이','Maui','Maui','3','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_lvl, use_yn, created_dt, modified_dt) VALUES ('183','카우아이','Kauai','Kauai','3','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_lvl, use_yn, created_dt, modified_dt) VALUES ('183','몰로카이','Molokai','Molokai','3','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_lvl, use_yn, created_dt, modified_dt) VALUES ('183','라나이','Lanai','Lanai','3','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_lvl, use_yn, created_dt, modified_dt) VALUES ('185','샌프란시스코','San Francisco','SF','3','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_lvl, use_yn, created_dt, modified_dt) VALUES ('185','샌디에이고','San Diego','SD','3','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_lvl, use_yn, created_dt, modified_dt) VALUES ('185','로스앤젤레스','LOS ANGELS','LA','3','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_lvl, use_yn, created_dt, modified_dt) VALUES ('186','씨애틀','Seattle','SEA','3','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_lvl, use_yn, created_dt, modified_dt) VALUES ('186','타코마','Tacoma','Tacoma','3','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_lvl, use_yn, created_dt, modified_dt) VALUES ('187','라스베가스','Las Vegas','LV','3','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_lvl, use_yn, created_dt, modified_dt) VALUES ('188','뉴욕','New York','NY','3','Y', now(), now());