INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_lvl, use_yn, created_dt, modified_dt) VALUES ('22','여행사','Travel agency', '','1','Y',now(),now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_lvl, use_yn, created_dt, modified_dt) VALUES ('22','옵션업체','Option Company','','1','Y',now(),now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_lvl, use_yn, created_dt, modified_dt) VALUES ('22','호텔','Hotel', '','1','Y',now(),now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_lvl, use_yn, created_dt, modified_dt) VALUES ('22','식당','Restaurant', '','1','Y',now(),now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_lvl, use_yn, created_dt, modified_dt) VALUES ('22','자동차수리','Mechanic','','1','Y',now(),now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_lvl, use_yn, created_dt, modified_dt) VALUES ('22','쇼핑','Shopping', '','1','Y',now(),now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_lvl, use_yn, created_dt, modified_dt) VALUES ('22','기타','Others', '','1','Y',now(),now());


INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_lvl, use_yn, created_dt, modified_dt) VALUES ('3','호텔','Hotel', '', '1','Y',now(),now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_lvl, use_yn, created_dt, modified_dt) VALUES ('3','옵션투어','Option Tour','','1','Y',now(),now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_lvl, use_yn, created_dt, modified_dt) VALUES ('3','식당','Restaurant', '','1','Y',now(),now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_lvl, use_yn, created_dt, modified_dt) VALUES ('3','골프','Golf', '','1','Y',now(),now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_lvl, use_yn, created_dt, modified_dt) VALUES ('3','선물','Mechanic','','1','Y',now(),now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_lvl, use_yn, created_dt, modified_dt) VALUES ('3','렌트카','Gift', '','1','Y',now(),now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_lvl, use_yn, created_dt, modified_dt) VALUES ('3','셔틀','Shuttle', '','1','Y',now(),now());

INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_ord, code_abb, code_kr, code_en) VALUES ('518', 1, 'Y', now(), now(), 1,'', '아쿠아', 'Aqua');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_ord, code_abb, code_kr, code_en) VALUES ('518', 1, 'Y', now(), now(), 2,'', '애스톤', 'Aston');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_ord, code_abb, code_kr, code_en) VALUES ('518', 1, 'Y', now(), now(), 3,'', '캐슬리조트', 'Castle Resort');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_ord, code_abb, code_kr, code_en) VALUES ('518', 1, 'Y', now(), now(), 4,'', '페어몬트', 'Fairmont');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_ord, code_abb, code_kr, code_en) VALUES ('518', 1, 'Y', now(), now(), 5,'', '포시즌리조트', 'Four seasons Resort');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_ord, code_abb, code_kr, code_en) VALUES ('518', 1, 'Y', now(), now(), 6,'', '하와이안호텔&리조트', 'Hawaiian Hotels & Resorts');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_ord, code_abb, code_kr, code_en) VALUES ('518', 1, 'Y', now(), now(), 7,'', '힐튼', 'Hilton');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_ord, code_abb, code_kr, code_en) VALUES ('518', 1, 'Y', now(), now(), 8,'', '하야트', 'Hyatt');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_ord, code_abb, code_kr, code_en) VALUES ('518', 1, 'Y', now(), now(), 9,'', '메리엇', 'Marriott');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_ord, code_abb, code_kr, code_en) VALUES ('518', 1, 'Y', now(), now(), 10,'', '아웃리거', 'Outrigger');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_ord, code_abb, code_kr, code_en) VALUES ('518', 1, 'Y', now(), now(), 11,'', '프린스', 'Prince');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_ord, code_abb, code_kr, code_en) VALUES ('518', 1, 'Y', now(), now(), 12,'', '스타우드', 'Starwood');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_ord, code_abb, code_kr, code_en) VALUES ('518', 1, 'Y', now(), now(), 13,'', '없음', 'None Group');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_ord, code_abb, code_kr, code_en) VALUES ('518', 1, 'Y', now(), now(), 14,'', '아쿠아애스톤', 'Aqua-Aston');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_ord, code_abb, code_kr, code_en) VALUES ('518', 1, 'Y', now(), now(), 15,'', '필라멘트 호스피탈리티', 'Filament Hospitality');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_ord, code_abb, code_kr, code_en) VALUES ('518', 1, 'Y', now(), now(), 16,'', '퍼시피카', 'Pacifica Hotels');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_ord, code_abb, code_kr, code_en) VALUES ('518', 1, 'Y', now(), now(), 17,'', '블랙스톤', 'Blackstone');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_ord, code_abb, code_kr, code_en) VALUES ('518', 1, 'Y', now(), now(), 18,'', '하이게이트', 'High Gate');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_ord, code_abb, code_kr, code_en) VALUES ('518', 1, 'Y', now(), now(), 19,'', '올스 호텔 & 리조트', 'OLS Hotels & Resorts');

INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('0', '040', '0', '0', 'Y', now(), now(), '1', '1', '침대유형', 'Bed Type', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('0', '050', '0', '0', 'Y', now(), now(), '1', '1', '추가비용', 'Option', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('0', '051', '0', '0', 'Y', now(), now(), '1', '1', '추가비용단위', 'Option', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('0', '030', '0', '0', 'Y', now(), now(), '1', '1', '호텔시설', 'Amenity', '');

INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('23', '0', '0', '0', 'Y', now(), now(), '1', '1', '어메니티정보', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('23', '0', '0', '0', 'Y', now(), now(), '1', '1', '취소규정', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('23', '0', '0', '0', 'Y', now(), now(), '1', '1', '취소규정(영문)', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('23', '0', '0', '0', 'Y', now(), now(), '1', '1', '특이사항', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('23', '0', '0', '0', 'Y', now(), now(), '1', '1', '특이사항(영문)', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('23', '0', '0', '0', 'Y', now(), now(), '1', '1', '소개', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('23', '0', '0', '0', 'Y', now(), now(), '1', '1', '소개(영문)', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('0', '0', '0', '0', 'Y', now(), now(), '1', '1', '기타', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('1', '0', '0', '0', 'Y', now(), now(), '1', '1', '기타(영문)', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('1', '0', '0', '0', 'Y', now(), now(), '1', '1', '바우처하단', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ( '0', '0', '0', 'Y', now(), now(), '1', '1', '바우처하단(영문)', '');

INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '인원추가', 'Additional Person', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '주차장', 'Parking', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '포트리지', 'Porterage', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '주차(발렛)', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '주차(셀프)', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '보조/간이침대(17세이하)', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '추가성인(클럽+스위트룸)', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '보조(간이)침대/Cribs', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '같은층', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '조식(알로하레이트)', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '스페셜세트디너(알로하레이트)', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '조식(그룹전용)', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '추가성인(룸 & 조식 &석식)', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '일요일브런치', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '손상보호비용', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '리조트피', 'Resort fee', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '애완동물(개 &고양이 온리)', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '컨티넨탈 부페(조식)', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '인원추가(펜트하우스)', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '허니문 비치 렌탈 프로그램', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '디너', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '시그니쳐디너(Signature Dinner)', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '디럭스 디너(Deluxe Dinner)', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '프리미엄디너(Premium Dinner)', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', 'KBG 디너', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '디너 뷔페(월-목)', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '디너 뷔페 (금-일)', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '휴일 디너 뷔페', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '24시간 피트니스 패스', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '호텔 투숙객용 골프 요금', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '특정 타워 보장', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '얼리체크인', 'Early Check-In', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '레이트체크아웃', 'Late Check-Out', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '칵테일(Cocktail)', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '레인보우 라나이 BF 부페스페셜', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '테마 저녁 부페', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '롯데 홈쇼핑 테마 디너뷔페', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '레인보우 라나이 BF 부페스페셜(어린이조식)', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '청소비', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '어메니티', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '게스트 라운지 이용', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574', '0', '0', '0', 'Y', now(), now(), '1', '1', '포트리지&메이드피', '');

INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574','0', '0','1', 'Y', now(), now(), '1', '1', '킹베드', 'King Bed', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574','0', '0','1', 'Y', now(), now(), '1', '1', '퀸베드', 'Queen Bed', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574','0', '0','1', 'Y', now(), now(), '1', '1', '트윈베드', 'Twin Bed', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574','0', '0','1', 'Y', now(), now(), '1', '1', '더블베드', 'Double Bed', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574','0', '0','1', 'Y', now(), now(), '1', '1', '킹소파베드', 'King sofa Bed', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574','0', '0','1', 'Y', now(), now(), '1', '1', '퀸소파베드', 'Q sofa Bed', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574','0', '0','1', 'Y', now(), now(), '1', '1', '트윈소파베드', 'T sofa Bed', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('574','0', '0','1', 'Y', now(), now(), '1', '1', '더블소파베드', 'D sofa Bed', '');


INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('589','0', '0','1', 'Y', now(), now(), '1', '1', '시설명', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('589','0', '0','1', 'Y', now(), now(), '1', '1', '인터넷', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('589','0', '0','1', 'Y', now(), now(), '1', '1', '금고', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('589','0', '0','1', 'Y', now(), now(), '1', '1', '수영장', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('589','0', '0','1', 'Y', now(), now(), '1', '1', '스파', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('589','0', '0','1', 'Y', now(), now(), '1', '1', '음료', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('589','0', '0','1', 'Y', now(), now(), '1', '1', '레스토랑', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('589','0', '0','1', 'Y', now(), now(), '1', '1', '헬스클럽', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('589','0', '0','1', 'Y', now(), now(), '1', '1', '조식쿠폰', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('589','0', '0','1', 'Y', now(), now(), '1', '1', '주차장', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('589','0', '0','1', 'Y', now(), now(), '1', '1', '카지노', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('589','0', '0','1', 'Y', now(), now(), '1', '1', '셔틀버스서비스', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('589','0', '0','1', 'Y', now(), now(), '1', '1', '비즈니스센터', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('589','0', '0','1', 'Y', now(), now(), '1', '1', '아이들액티비티', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('589','0', '0','1', 'Y', now(), now(), '1', '1', '조식 시간', '');

INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('518', '0', '1', 'Y', now(), now(), '1', '1', '호텔그룹선택', 'Group', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('518', '1', '1', 'Y', now(), now(), '1', '1', '아쿠아', 'Aqua', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('518', '2', '1', 'Y', now(), now(), '1', '1', '애스톤', 'Aston', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('518', '3', '1', 'Y', now(), now(), '1', '1', '캐슬리조트', 'Castle Resort', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('518', '4', '1', 'Y', now(), now(), '1', '1', '페어몬트', 'Fairmont', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('518', '5', '1', 'Y', now(), now(), '1', '1', '포시즌', 'Four seasons Resort', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('518', '6', '1', 'Y', now(), now(), '1', '1', '하와이안 호텔 & 리조트', 'Hawaiian Hotels & Resorts', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('518', '7', '1', 'Y', now(), now(), '1', '1', '힐튼', 'Hilton', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('518', '8', '1', 'Y', now(), now(), '1', '1', '하야트', 'Hyatt', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('518', '9', '1', 'Y', now(), now(), '1', '1', '메리엇', 'Marriott', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('518', '10', '1', 'Y', now(), now(), '1', '1', '아웃리거', 'Outrigger', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('518', '11', '1', 'Y', now(), now(), '1', '1', '프린스', 'Prince', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('518', '12', '1', 'Y', now(), now(), '1', '1', '스타우드', 'Starwood', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('518', '13', '1', 'Y', now(), now(), '1', '1', '아쿠아 애스톤', 'Aqua-Aston', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('518', '14', '1', 'Y', now(), now(), '1', '1', '필라멘트 호스털리티', 'Filament Hospitality', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('518', '15', '1', 'Y', now(), now(), '1', '1', '퍼시피카', 'Pacifica Hotels', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('518', '16', '1', 'Y', now(), now(), '1', '1', '블랙스톤', 'Blackstone', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('518', '17', '1', 'Y', now(), now(), '1', '1', '하이게이트', 'High Gate', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('518', '18', '1', 'Y', now(), now(), '1', '1', '올스 호텔 & 리조트', 'OLS Hotels and Resorts', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('518', '99', '1', 'Y', now(), now(), '1', '1', '그룹없음', 'None Group', '');


INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('613','0', '0','1', 'Y', now(), now(), '1', '1', '룸정보', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('613','0', '0','1', 'Y', now(), now(), '1', '1', '변기 근처 안전손잡이', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('613','0', '0','1', 'Y', now(), now(), '1', '1', '낮은 카운터/싱크대', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('613','0', '0','1', 'Y', now(), now(), '1', '1', '휠체어로 이용 가능', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('613','0', '0','1', 'Y', now(), now(), '1', '1', '무선인터넷 연결', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('613','0', '0','1', 'Y', now(), now(), '1', '1', '무선인터넷 연결(유료)', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('613','0', '0','1', 'Y', now(), now(), '1', '1', '지역전화 또는 수신자 부담 전화', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('613','0', '0','1', 'Y', now(), now(), '1', '1', '유선인터넷 연결', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('613','0', '0','1', 'Y', now(), now(), '1', '1', '유선인터넷 연결 (유료)', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('613','0', '0','1', 'Y', now(), now(), '1', '1', '라디오', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('613','0', '0','1', 'Y', now(), now(), '1', '1', 'LCD TV', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('613','0', '0','1', 'Y', now(), now(), '1', '1', '넷플릭스', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('613','0', '0','1', 'Y', now(), now(), '1', '1', '프리미엄 TV 채널', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('613','0', '0','1', 'Y', now(), now(), '1', '1', '유료영화', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('613','0', '0','1', 'Y', now(), now(), '1', '1', 'iPod 도킹 스테이션', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('613','0', '0','1', 'Y', now(), now(), '1', '1', 'DVD 플레이어', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('613','0', '0','1', 'Y', now(), now(), '1', '1', '목욕실', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('613','0', '0','1', 'Y', now(), now(), '1', '1', '커피/티 메이커 or 커피포트', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('613','0', '0','1', 'Y', now(), now(), '1', '1', '무료생수', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('613','0', '0','1', 'Y', now(), now(), '1', '1', '다리미/다리미판', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('613','0', '0','1', 'Y', now(), now(), '1', '1', '헤어드라이어', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('613','0', '0','1', 'Y', now(), now(), '1', '1', '냉장고', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('613','0', '0','1', 'Y', now(), now(), '1', '1', '전자렌지', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('613','0', '0','1', 'Y', now(), now(), '1', '1', '에어컨', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('613','0', '0','1', 'Y', now(), now(), '1', '1', '온도조절', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('613','0', '0','1', 'Y', now(), now(), '1', '1', '책상', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('613','0', '0','1', 'Y', now(), now(), '1', '1', '금고', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('613','0', '0','1', 'Y', now(), now(), '1', '1', '객실내 소파', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('613','0', '0','1', 'Y', now(), now(), '1', '1', '욕조', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('613','0', '0','1', 'Y', now(), now(), '1', '1', '목욕가운', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('613','0', '0','1', 'Y', now(), now(), '1', '1', '슬리퍼', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('613','0', '0','1', 'Y', now(), now(), '1', '1', '목욕가운(요청시)', '');
INSERT INTO COM_CODE (upr_code_uuid, code_ord, code_lvl, use_yn, created_dt, modified_dt, created_by, modified_by, code_kr, code_en, code_abb) VALUES ('613','0', '0','1', 'Y', now(), now(), '1', '1', '베란다', '');

