INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'ENG', '영어', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'JPN', '일어', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'USER_R', '사용자관리 읽기', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'USER_WU', '사용자관리 편집', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'USER_D', '사용자관리 삭제', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'FILE_UP', '파일업로드', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'FILE_D', '파일삭제', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'NOTICE_R', '공지사항 읽기', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'NOTICE_WU', '공지사항 편집', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'NOTICE_D', '공지사항 삭제', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'ACCOUNT_R', '회계 읽기', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'ACCOUNT_WU', '회계 편집', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'ACCOUNT_D', '회계 삭제', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'CONT_R', '상품관리 읽기', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'CONT_WU', '상품관리 편집', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'CONT_D', '상품관리 삭제', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'PRICE_R', '가격관리 읽기', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'PRICE_WU', '가격관리 편집', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'PRICE_D', '가격관리 삭제', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'SET_R', '설정 읽기', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'SET_WU', '설정 편집', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'SET_D', '설정 삭제', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'REQ_R', '요청 읽기', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'REQ_WU', '요청 편집', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'REQ_D', '요청 삭제', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'REPORT_R', '리포트 읽기', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'REPORT_WU', '리포트 편집', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'REPORT_D', '리포트 삭제', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'BOOK_R', '예약관리 읽기', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'BOOK_WU', '예약관리 편집', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'BOOK_D', '예약관리 삭제', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'OFF_R', '휴일관리 읽기', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'OFF_WU', '휴일관리 편집', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'OFF_D', '휴일관리 삭제', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'INVENTORY_R', '비품관리 읽기', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'INVENTORY_WU', '비품관리 편집', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'INVENTORY_D', '비품관리 삭제', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'CONFIRM_R', '확정서 읽기', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'CONFIRM_WU', '확정서 편집', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'CONFIRM_D', '확정서 삭제', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'ASSIGN_R', '배정 읽기', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'ASSIGN_WU', '배정 편집', now());
INSERT INTO COM_MENU_AUTH (`auth_yn`, `menu_auth_name_eng`, `menu_auth_name`, `modified_dt`) VALUES('Y', 'ASSIGN_D', '배정 삭제', now());