INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('30','서울','Seoul','Seoul','011','2','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('30','부산','Busan','Busan','021','2','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('30','대구','Daegu','Daegu','022','2','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('30','인천','Incheon','Incheon','023','2','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('30','광주','Gwangju','Gwangju','024','2','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('30','대전','Daejeon','Daejeon','025','2','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('30','울산','Ulsan','Ulsan','026','2','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('30','세종특별자치시','Sejong','Sejong','029','2','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('30','경기도','Gyeonggi-do','Gyeonggi-do','031','2','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('30','강원도','Gangwon-do','Gangwon-do','032','2','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('30','충청북도','Chungcheongbuk-do','Chungcheongbuk-do','033','2','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('30','충청남도','Chungcheongnam-do','Chungcheongnam-do','034','2','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('30','전라북도','Jeollabuk-do','Jeollabuk-do','035','2','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('30','전라남도','Jeollanam-do','Jeollanam-do','036','2','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('30','경상북도','Gyeongsangbuk-do','Gyeongsangbuk-do','037','2','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('30','경상남도','Gyeongsangnam-do','Gyeongsangnam-do','038','2','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('30','제주','Jeju','Jeju','039','2','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('31','하와이','HAWAII','HI','001','2','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('31','괌','GUAM','GU','002','2','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('31','캘리포니아','CALIFORNIA','CA','003','2','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('31','워싱턴','WASHINGTON','WA','004','2','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('31','네바다','NEVADA','NV','005','2','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('31','뉴욕','NEW YORK','NY','006','2','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('31','죠지아','GEORGIA		GA','007','2','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('31','테네시','TENNESSEE','TN','008','2','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('31','텍사스','TEXAS','TX','009','2','Y', now(), now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('31','미시간','MICHIGAN','MI','010','2','Y', now(), now());