INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('18','직책선택','Select','','000','1','Y',now(),now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('18','사원','Staff','','001','1','Y',now(),now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('18','대리','Assistant manager','','002','1','Y',now(),now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('18','과장','Manager','','003','1','Y',now(),now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('18','차장','Deputy general manager','','004','1','Y',now(),now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('18','부장','General Manager','','005','1','Y',now(),now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('18','실장','Head of a department','','006','1','Y',now(),now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('18','이사','Director','','007','1','Y',now(),now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('18','소장','Supervisor','','008','1','Y',now(),now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('18','대표이사','대표이사','','009','1','Y',now(),now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('18','계장','Gaejang','','010','1','Y',now(),now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('18','주임','Juim','','011','1','Y',now(),now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('18','팀장','Team Manager','','012','1','Y',now(),now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('18','지점장','Area Director','','013','1','Y',now(),now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('18','상무','Sangmu','','014','1','Y',now(),now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('18','전임','Junim','','015','1','Y',now(),now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('18','매니저','Manager','','016','1','Y',now(),now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('18','계장','Assistant manager','','017','1','Y',now(),now());
INSERT INTO COM_CODE (upr_code_uuid, code_kr, code_en, code_abb, code_value, code_lvl, use_yn, created_dt, modified_dt) VALUES ('18','전무','Executive Director','','018','1','Y',now(),now());