//호텔
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('30',1, 'Y',now(),now(),'넷가','NET','NET');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('30',1, 'Y',now(),now(),'PP','PP','PP');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('30',1, 'Y',now(),now(),'JJ','JJ','JJ');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('30',1, 'Y',now(),now(),'SS','SS','SS');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('30',1, 'Y',now(),now(),'Hana Tour Free(Hotel)','Hana Tour Free(Hotel)','');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('30',1, 'Y',now(),now(),'Tour Park','Tour Park','Tour Park');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('30',1, 'Y',now(),now(),'블루하와이','Blue Hawaii Retail','Blue Hawaii Retail');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('30',1, 'Y',now(),now(),'블루하와이소매가','','');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('30',1, 'Y',now(),now(),'Global','Global','Global');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('30',1, 'Y',now(),now(),'판매제외등급','Exclude','');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('30',1, 'Y',now(),now(),'랜드사가','Land','Land');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('30',1, 'Y',now(),now(),'Tour Marble','Tour Marble','Tour Marble');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('30',1, 'Y',now(),now(),'인터파크호텔','Interpark Hotel','Interpark Hotel');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('30',1, 'Y',now(),now(),'상품판매용','','');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('30',1, 'Y',now(),now(),'트래블픽','','');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('30',1, 'Y',now(),now(),'레드코코','Red Coco','Red Coco');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('30',1, 'Y',now(),now(),'CM Travel in Hawaii','CM Travel in Hawaii','CM Travel in Hawaii');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('30',1, 'Y',now(),now(),'스페셜','Special','Special');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('30',1, 'Y',now(),now(),'라벨라','Labella','Labella');
//옵션
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('31',1, 'Y',now(),now(),'넷가','NET','NET');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('31',1, 'Y',now(),now(),'고객판매가','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('31',1, 'Y',now(),now(),'여행사가','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('31',1, 'Y',now(),now(),'랜드사가','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('31',1, 'Y',now(),now(),'블루하와이','Blue Hawaii Retail','Blue Hawaii Retail');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('31',1, 'Y',now(),now(),'블루하와이소매가','','');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('31',1, 'Y',now(),now(),'팜투어','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('31',1, 'Y',now(),now(),'선판매랜드사','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('31',1, 'Y',now(),now(),'선판매여행사','','');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('31',1, 'Y',now(),now(),'데스크','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('31',1, 'Y',now(),now(),'레드코코','Red Coco','Red Coco');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('31',1, 'Y',now(),now(),'퍼시픽투어','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('31',1, 'Y',now(),now(),'하와이푸디','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('31',1, 'Y',now(),now(),'모든메가','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('31',1, 'Y',now(),now(),'GW 데스크','','');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('31',1, 'Y',now(),now(),'하나투어고객','Hana Tour','Hana Tour');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('31',1, 'Y',now(),now(),'본토상품현지','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('31',1, 'Y',now(),now(),'판매등급제외','Exclude', 'Exclude');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('31',1, 'Y',now(),now(),'슈퍼베케이션','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('31',1, 'Y',now(),now(),'다이닝카드할인가','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('31',1, 'Y',now(),now(),'H.I.S ','H.I.S','H.I.S');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('31',1, 'Y',now(),now(),'올로마나','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('31',1, 'Y',now(),now(),'라벨라','Labella','Labella');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('31',1, 'Y',now(),now(),'르네상스','Renaissance','Renaissance');
//렌트카
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('32',1, 'Y',now(),now(),'넷가','NET','NET');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('32',1, 'Y',now(),now(),'고객판매가','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('32',1, 'Y',now(),now(),'여행사가','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('32',1, 'Y',now(),now(),'랜드사가','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('32',1, 'Y',now(),now(),'블루하와이','Blue Hawaii Retail','Blue Hawaii Retail');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('32',1, 'Y',now(),now(),'블루하와이소매가','','');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('32',1, 'Y',now(),now(),'선판매랜드사','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('32',1, 'Y',now(),now(),'선판매여행사','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('32',1, 'Y',now(),now(),'데스크','','');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('32',1, 'Y',now(),now(),'레드코코','Red Coco','Red Coco');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('32',1, 'Y',now(),now(),'퍼시픽투어','','');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('32',1, 'Y',now(),now(),'트래블픽','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('32',1, 'Y',now(),now(),'모든메가','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('32',1, 'Y',now(),now(),'GW 데스크','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('32',1, 'Y',now(),now(),'가자하와이','','');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('32',1, 'Y',now(),now(),'투어파크코리아','Hana Tour','Hana Tour');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('32',1, 'Y',now(),now(),'하와이넘버원','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('32',1, 'Y',now(),now(),'스마트하와이투어','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('32',1, 'Y',now(),now(),'본토상품현지','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('32',1, 'Y',now(),now(),'판매등급제외','Exclude', 'Exclude');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('32',1, 'Y',now(),now(),'팜투어','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('32',1, 'Y',now(),now(),'29아프로','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('32',1, 'Y',now(),now(),'교원KRT','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('32',1, 'Y',now(),now(),'라벨라','Labella','Labella');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('32',1, 'Y',now(),now(),'르네상스','Labella','Labella');
//식당
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('33',1, 'Y',now(),now(),'넷가','NET','NET');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('33',1, 'Y',now(),now(),'여행사가','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('33',1, 'Y',now(),now(),'블루하와이','Blue Hawaii Retail','Blue Hawaii Retail');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('33',1, 'Y',now(),now(),'블루하와이소매가','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('33',1, 'Y',now(),now(),'레드코코','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('33',1, 'Y',now(),now(),'판매등급제외','Exclude','Exclude');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('33',1, 'Y',now(),now(),'고객판매가','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('33',1, 'Y',now(),now(),'하와이푸디','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('33',1, 'Y',now(),now(),'다이닝카드할인가','','');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('33',1, 'Y',now(),now(),'교원KRT','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('33',1, 'Y',now(),now(),'라벨라','Labella','Labella');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('33',1, 'Y',now(),now(),'르네상스','Labella','Labella');
//패키지/허니문일반
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('36',1, 'Y',now(),now(),'없음','','');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('36',1, 'Y',now(),now(),'일반','','');

//패키지 전용
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'없음','','');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'넷가','NET','NET');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'하나투어','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'TLM','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'블루하와이','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'천생연분','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'다이나믹','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'노랑풍선','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'피피랜드','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'롯데관광','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'여행&라이프','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'한진관광','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'레드캡','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'참좋은여행','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'본토','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'LA아주','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'인포투어','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'하나투어USA','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'투어클릭','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'트래블픽','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'게스투어','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'투어마블','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'엑스포에이치트래블','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'참좋은프리미엄','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'29아프로','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'다이렉트허니문','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'대구로뎀투어','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'대구프렌즈투어','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'투어빈','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'코리아투어','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'허니문사랑','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'드림리조트','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'패밀리투어','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'교원KRT','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'어썸투어상품','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'인터파크','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('37',1, 'Y',now(),now(),'라벨라','', '');
//허니문전용
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'없음','','');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'넷가','NET','NET');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'하나투어','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'TLM','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'블루하와이','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'천생연분','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'다이나믹','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'노랑풍선','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'피피랜드','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'롯데관광','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'여행&라이프','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'한진관광','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'레드캡','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'참좋은여행','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'본토','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'LA아주','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'인포투어','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'하나투어USA','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'투어클릭','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'트래블픽','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'게스투어','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'투어마블','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'엑스포에이치트래블','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'참좋은프리미엄','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'29아프로','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'다이렉트허니문','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'대구로뎀투어','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'대구프렌즈투어','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'투어빈','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'코리아투어','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'허니문사랑','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'드림리조트','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'패밀리투어','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'교원KRT','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'어썸투어상품','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'인터파크','', '');
INSERT INTO COM_CODE (upr_code_uuid, code_lvl, use_yn, created_dt, modified_dt, code_kr, code_en, code_abb) VALUES ('39',1, 'Y',now(),now(),'라벨라','', '');





