import { getNumberMemberValue } from 'src/utils/helpers/ConstructorHelper';

export interface IEmpForm {
  empUuid: number | 0;
  empEmail: string | '';
  empKor: string | '';
  password: string | '';
  username: string | '';
  empEng: string | '';
  empImg: string | '';
  empDiv: number | 0;
  empRole: number | 0;
  empTitle: number | 0;
  empWorkType: number | 0;
  empPhone: string | '';
  empWorkPhone: string | '';
  empAddress1: string | '';
  empAddress2: string | '';
  empCity: string | '';
  empDob: string | '';
  empDobType: number | 0;
  empEmailBook: string | '';
  empState: string | '';
  empZip: string | '';
  empBeginDt: string | '';
  empMemo: string | '';
  empStatus: number | 0;
  empEndDt: string | '';
  empCountry: number | 0;
  modifiedBy: number | 0;
  modifiedDt: Date | '';
  backColor: string | '';
  fontColor: string | '';
}

export class EmpForm implements IEmpForm {
  public empUuid: number | 0;
  public empEmail: string | '';
  public empKor: string | '';
  public password: string | '';
  public username: string | '';
  public empEng: string | '';
  public empImg: string | '';
  public empDiv: number | 0;
  public empRole: number | 0;
  public empTitle: number | 0;
  public empWorkType: number | 0;
  public empPhone: string | '';
  public empWorkPhone: string | '';
  public empAddress1: string | '';
  public empAddress2: string | '';
  public empCity: string | '';
  public empDob: string | '';
  public empDobType: number | 0;
  public empEmailBook: string | '';
  public empState: string | '';
  public empZip: string | '';
  public empBeginDt: string | '';
  public empMemo: string | '';
  public empStatus: number | 0;
  public empEndDt: string | '';
  public empCountry: number | 0;
  public modifiedBy: number | 0;
  public modifiedDt: Date | '';
  public backColor: string | '';
  public fontColor: string | '';

  constructor(obj?: IEmpForm) {
    this.empUuid = getNumberMemberValue(obj && obj.empUuid);
    this.empEmail = (obj && obj.empEmail) || '';
    this.empKor = (obj && obj.empKor) || '';
    this.password = (obj && obj.password) || '';
    this.username = (obj && obj.username) || '';
    this.empEng = (obj && obj.empEng) || '';
    this.empImg = (obj && obj.empImg) || '';
    this.empDiv = (obj && obj.empDiv) || 0;
    this.empRole = (obj && obj.empRole) || 0;
    this.empTitle = (obj && obj.empTitle) || 0;
    this.empWorkType = (obj && obj.empWorkType) || 0;
    this.empPhone = (obj && obj.empPhone) || '';
    this.empWorkPhone = (obj && obj.empWorkPhone) || '';
    this.empAddress1 = (obj && obj.empAddress1) || '';
    this.empAddress2 = (obj && obj.empAddress2) || '';
    this.empCity = (obj && obj.empCity) || '';
    this.empDob = (obj && obj.empDob) || '';
    this.empDobType = (obj && obj.empDobType) || 0;
    this.empEmailBook = (obj && obj.empEmailBook) || '';
    this.empState = (obj && obj.empState) || '';
    this.empZip = (obj && obj.empZip) || '';
    this.empBeginDt = (obj && obj.empBeginDt) || '';
    this.empMemo = (obj && obj.empMemo) || '';
    this.empStatus = (obj && obj.empStatus) || 0;
    this.empEndDt = (obj && obj.empEndDt) || '';
    this.empCountry = (obj && obj.empCountry) || 0;
    this.modifiedBy = (obj && obj.modifiedBy) || 0;
    this.modifiedDt = (obj && obj.modifiedDt) || '';
    this.backColor = (obj && obj.backColor) || '';
    this.fontColor = (obj && obj.fontColor) || '';
  }
}
